/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CourseRecommendation {
  'courses' : Array<string>,
  'skill' : string,
}
export interface InterviewSession {
  'id' : bigint,
  'answers' : Array<string>,
  'role' : string,
  'feedback' : string,
  'score' : bigint,
  'timestamp' : Time,
  'questions' : Array<string>,
}
export interface Resume {
  'id' : bigint,
  'content' : string,
  'suggestions' : Array<string>,
  'analysisScore' : bigint,
  'skillsExtracted' : Array<string>,
  'timestamp' : Time,
  'missingSkills' : Array<string>,
}
export type Time = bigint;
export interface UserProfile {
  'id' : Principal,
  'name' : string,
  'createdAt' : Time,
  'resumes' : Array<Resume>,
  'email' : string,
  'interviews' : Array<InterviewSession>,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createOrUpdateProfile' : ActorMethod<[string, string], undefined>,
  'deleteResume' : ActorMethod<[bigint], undefined>,
  'getAllCourseRecommendations' : ActorMethod<[], Array<CourseRecommendation>>,
  'getAllUserProfiles' : ActorMethod<[], Array<UserProfile>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCourseRecommendations' : ActorMethod<
    [string],
    [] | [CourseRecommendation]
  >,
  'getInterviewHistory' : ActorMethod<[Principal], Array<InterviewSession>>,
  'getProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getResumes' : ActorMethod<[Principal], Array<Resume>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserStats' : ActorMethod<[], Array<[Principal, bigint, bigint]>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveCourseRecommendation' : ActorMethod<[string, Array<string>], undefined>,
  'saveInterview' : ActorMethod<
    [string, Array<string>, Array<string>, bigint, string],
    undefined
  >,
  'saveResume' : ActorMethod<
    [string, Array<string>, bigint, Array<string>, Array<string>],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];