/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const CourseRecommendation = IDL.Record({
  'courses' : IDL.Vec(IDL.Text),
  'skill' : IDL.Text,
});
export const Time = IDL.Int;
export const Resume = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'suggestions' : IDL.Vec(IDL.Text),
  'analysisScore' : IDL.Nat,
  'skillsExtracted' : IDL.Vec(IDL.Text),
  'timestamp' : Time,
  'missingSkills' : IDL.Vec(IDL.Text),
});
export const InterviewSession = IDL.Record({
  'id' : IDL.Nat,
  'answers' : IDL.Vec(IDL.Text),
  'role' : IDL.Text,
  'feedback' : IDL.Text,
  'score' : IDL.Nat,
  'timestamp' : Time,
  'questions' : IDL.Vec(IDL.Text),
});
export const UserProfile = IDL.Record({
  'id' : IDL.Principal,
  'name' : IDL.Text,
  'createdAt' : Time,
  'resumes' : IDL.Vec(Resume),
  'email' : IDL.Text,
  'interviews' : IDL.Vec(InterviewSession),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createOrUpdateProfile' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'deleteResume' : IDL.Func([IDL.Nat], [], []),
  'getAllCourseRecommendations' : IDL.Func(
      [],
      [IDL.Vec(CourseRecommendation)],
      ['query'],
    ),
  'getAllUserProfiles' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCourseRecommendations' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(CourseRecommendation)],
      ['query'],
    ),
  'getInterviewHistory' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(InterviewSession)],
      ['query'],
    ),
  'getProfile' : IDL.Func([IDL.Principal], [IDL.Opt(UserProfile)], ['query']),
  'getResumes' : IDL.Func([IDL.Principal], [IDL.Vec(Resume)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserStats' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Nat, IDL.Nat))],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveCourseRecommendation' : IDL.Func([IDL.Text, IDL.Vec(IDL.Text)], [], []),
  'saveInterview' : IDL.Func(
      [IDL.Text, IDL.Vec(IDL.Text), IDL.Vec(IDL.Text), IDL.Nat, IDL.Text],
      [],
      [],
    ),
  'saveResume' : IDL.Func(
      [
        IDL.Text,
        IDL.Vec(IDL.Text),
        IDL.Nat,
        IDL.Vec(IDL.Text),
        IDL.Vec(IDL.Text),
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const CourseRecommendation = IDL.Record({
    'courses' : IDL.Vec(IDL.Text),
    'skill' : IDL.Text,
  });
  const Time = IDL.Int;
  const Resume = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'suggestions' : IDL.Vec(IDL.Text),
    'analysisScore' : IDL.Nat,
    'skillsExtracted' : IDL.Vec(IDL.Text),
    'timestamp' : Time,
    'missingSkills' : IDL.Vec(IDL.Text),
  });
  const InterviewSession = IDL.Record({
    'id' : IDL.Nat,
    'answers' : IDL.Vec(IDL.Text),
    'role' : IDL.Text,
    'feedback' : IDL.Text,
    'score' : IDL.Nat,
    'timestamp' : Time,
    'questions' : IDL.Vec(IDL.Text),
  });
  const UserProfile = IDL.Record({
    'id' : IDL.Principal,
    'name' : IDL.Text,
    'createdAt' : Time,
    'resumes' : IDL.Vec(Resume),
    'email' : IDL.Text,
    'interviews' : IDL.Vec(InterviewSession),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createOrUpdateProfile' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'deleteResume' : IDL.Func([IDL.Nat], [], []),
    'getAllCourseRecommendations' : IDL.Func(
        [],
        [IDL.Vec(CourseRecommendation)],
        ['query'],
      ),
    'getAllUserProfiles' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCourseRecommendations' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(CourseRecommendation)],
        ['query'],
      ),
    'getInterviewHistory' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(InterviewSession)],
        ['query'],
      ),
    'getProfile' : IDL.Func([IDL.Principal], [IDL.Opt(UserProfile)], ['query']),
    'getResumes' : IDL.Func([IDL.Principal], [IDL.Vec(Resume)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserStats' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Nat, IDL.Nat))],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveCourseRecommendation' : IDL.Func(
        [IDL.Text, IDL.Vec(IDL.Text)],
        [],
        [],
      ),
    'saveInterview' : IDL.Func(
        [IDL.Text, IDL.Vec(IDL.Text), IDL.Vec(IDL.Text), IDL.Nat, IDL.Text],
        [],
        [],
      ),
    'saveResume' : IDL.Func(
        [
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Nat,
          IDL.Vec(IDL.Text),
          IDL.Vec(IDL.Text),
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };